#! /bin/sh
sxhkd &

bspc monitor VGA-0  -d //1 //2 //3 //4 //5 
bspc monitor LVDS   -d //6 //7 //8 //9 //0

bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Main.py state=floating border=off
bspc rule -a feh state=floating
bspc rule -a Xscreensaver state=floating
bspc rule -a mpv desktop='^2'

#autostart

urxvtd &
xcompmgr &
xscreensaver -no-splash &
setxkbmap de &
yeahconsole &
urxvt -title "//DASH" -e '/home/bronko/bin/muxdash' &
#pypanel &
(pypanel & sleep 3 && dhcpcd-gtk & /home/bronko/.local/bin/moc-tray & pasystray) &
#EXPERIMENTAL
#(sleep 3; /home/bronko/.local/bin/menutray) &


