#! /bin/sh
xscreensaver -no-splash &
setxkbmap de &
sxhkd &
xcompmgr &
xterm -title "//DASH" -e '/home/bronko/bin/muxdash' &
pypanel &

#xrandr --output VGA-0 --left-of LVDS --mode 1360x768 

bspc monitor LVDS  -d //1 //2 //3 //4 //5 
bspc monitor VGA-0 -d //6 //7 //8 //9 //0

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#feh --bg-scale ~/downloads/FE*

